var CustomersData = 
	{Rows: [
		{
			"CustomerID": "632415451",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC":"崇明区局",
			"ContactTitle": "崇明分局",
			"Address": "南门*崇明*",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324629",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼入",
			"bh":"1",
			"rw_zt":"执行中",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜宽带"
		},
		{
			"CustomerID": "632415312",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC":"西区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324628",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"2",
			"rw_zt":"未完成",
			"lqsl":"5/2",
			"BUSINESS_TYPE":"光宽带"
		},
		{
			"CustomerID": "632415452",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC":"莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324627",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"3",
			"rw_zt":"执行中",
			"lqsl":"5/3",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415453",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324626",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"4",
			"rw_zt":"未完成",
			"lqsl":"10/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415454",
			"CompanyName": "FH1100082616",
			"ContactName": "否",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324625",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"5",
			"rw_zt":"未完成",
			"lqsl":"10/5",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324624",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"6",
			"rw_zt":"未完成",
			"lqsl":"10/6",
			"BUSINESS_TYPE":"光宽带"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324623",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼入",
			"bh":"7",
			"rw_zt":"未完成",
			"lqsl":"10/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324622",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"8",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324621",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"9",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324621",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"10",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324620",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"11",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324619",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"12",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324618",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"13",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
		{
			"CustomerID": "632415456",
			"CompanyName": "FH1100082616",
			"ContactName": "是",
			"RC": "莘闵区局",
			"ContactTitle": "虹桥分局",
			"Address": "濮家桥",
			"City": "2016-11-20 00:00:34",
			"Region": "宽带",
			"PostalCode": "宽带后付费",
			"Country": "用户无法上网，现象不明",
			"DECLARATION_REMARK":"测试",
			"Phone": "505",
			"Fax": "未检测到异常",
			"DECLARATION_LINKINFO":"*",
			"IS_SECOND_REDEAL":"ceshi",
			"CLOSEED_WAY":"一级",
			"CLOSEED_TIMELENGTH":"0",
			"ACCEPTED_SOURCE":"翼排障",
			"FIRST_AGENT_USERID":"SHWT",
			"FIRST_REDEAL_WORKID":"SHWT",
			"FIRST_REDEAL_SUGGEST":"PON测试未完成;账号检查未完成;杀死进程未完成;速率同步未完成;PVC绑定未完成;建议派修方向:区局(外线)",
			"FIRST_REDEAL_CLOSEDCODE":"设备重启",
			"SECOND_REDEAL_CLOSEDCODE":"ceshi",
			"SECOND_REDEAL_REMARK":"*",
			"SECOND_WORKID":"*",
			"SECOND_CLOSETIME":"1900-01-01 00:00:00",
			"REPAIR_TIME":"1900-01-01 00:00:00",
			"REPAIR_WORKID":"*",
			"REPAIR_DIRECTION":"不详",
			"THREE_ERROR_TYPE":"*",
			"THREE_ERROR_REPAIR_CODE":"*",
			"THREE_WORKID":"*",
			"THREE_REPAIR_TIME":"1900-01-01 00:00:00",
			"serial_cdma":"3324617",
			"appeal_status":"正常",
			"dir_num":"17302103617",
			"zj_workid":"AA000",
			"sl_workid":"AKD4059",
			"sl_name":"袁浩栋",
			"is_tl9000":"是",
			"cl_qk":"正常",
			"hg_cd":"合格",
			"jc_check":"无法上网",
			"cl_jg":"测试",
			"rg_zj":"无需转接",
			"TELSUM_TYPE":"申告",
			"ERROR_SOURCE":"电话",
			"Paper_status":"待话务员处理",
			"qc_type":"录音评分",
			"huru":"呼出",
			"bh":"14",
			"rw_zt":"未完成",
			"lqsl":"5/1",
			"BUSINESS_TYPE":"铜固网"
		},
	],
	Total: 14
};