
package cn.sh.ideal.voicecyber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWebSDK", targetNamespace = "http://www.voicecyber.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWebSDK {


    /**
     * 
     * @param voiceid
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetVoiceIPByVoiceID", action = "http://www.voicecyber.com/IWebSDK/GetVoiceIPByVoiceID")
    @WebResult(name = "GetVoiceIPByVoiceIDResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetVoiceIPByVoiceID", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetVoiceIPByVoiceID")
    @ResponseWrapper(localName = "GetVoiceIPByVoiceIDResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetVoiceIPByVoiceIDResponse")
    public WebSDKReturn getVoiceIPByVoiceID(
        @WebParam(name = "voiceid", targetNamespace = "http://www.voicecyber.com/")
        Integer voiceid);

    /**
     * 
     * @param voiceid
     * @param getVoiceCountResult
     */
    @WebMethod(operationName = "GetVoiceCount", action = "http://www.voicecyber.com/IWebSDK/GetVoiceCount")
    @RequestWrapper(localName = "GetVoiceCount", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetVoiceCount")
    @ResponseWrapper(localName = "GetVoiceCountResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetVoiceCountResponse")
    public void getVoiceCount(
        @WebParam(name = "voiceid", targetNamespace = "http://www.voicecyber.com/", mode = WebParam.Mode.INOUT)
        Holder<ArrayOfint> voiceid,
        @WebParam(name = "GetVoiceCountResult", targetNamespace = "http://www.voicecyber.com/", mode = WebParam.Mode.OUT)
        Holder<WebSDKReturn> getVoiceCountResult);

    /**
     * 
     * @param voiceid
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetChannelCountByVoiceID", action = "http://www.voicecyber.com/IWebSDK/GetChannelCountByVoiceID")
    @WebResult(name = "GetChannelCountByVoiceIDResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetChannelCountByVoiceID", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetChannelCountByVoiceID")
    @ResponseWrapper(localName = "GetChannelCountByVoiceIDResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetChannelCountByVoiceIDResponse")
    public WebSDKReturn getChannelCountByVoiceID(
        @WebParam(name = "voiceid", targetNamespace = "http://www.voicecyber.com/")
        Integer voiceid);

    /**
     * 
     * @param extension
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetChannelByExt", action = "http://www.voicecyber.com/IWebSDK/GetChannelByExt")
    @WebResult(name = "GetChannelByExtResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetChannelByExt", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetChannelByExt")
    @ResponseWrapper(localName = "GetChannelByExtResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetChannelByExtResponse")
    public WebSDKReturn getChannelByExt(
        @WebParam(name = "extension", targetNamespace = "http://www.voicecyber.com/")
        String extension);

    /**
     * 
     * @param extension
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetRefID", action = "http://www.voicecyber.com/IWebSDK/GetRefID")
    @WebResult(name = "GetRefIDResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetRefID", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRefID")
    @ResponseWrapper(localName = "GetRefIDResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRefIDResponse")
    public WebSDKReturn getRefID(
        @WebParam(name = "extension", targetNamespace = "http://www.voicecyber.com/")
        String extension);

    /**
     * 
     * @param refID
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetFileHttpPath", action = "http://www.voicecyber.com/IWebSDK/GetFileHttpPath")
    @WebResult(name = "GetFileHttpPathResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetFileHttpPath", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetFileHttpPath")
    @ResponseWrapper(localName = "GetFileHttpPathResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetFileHttpPathResponse")
    public WebSDKReturn getFileHttpPath(
        @WebParam(name = "RefID", targetNamespace = "http://www.voicecyber.com/")
        String refID);

    /**
     * 
     * @param reservedFields
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetFilePathbyReservedFields", action = "http://www.voicecyber.com/IWebSDK/GetFilePathbyReservedFields")
    @WebResult(name = "GetFilePathbyReservedFieldsResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetFilePathbyReservedFields", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetFilePathbyReservedFields")
    @ResponseWrapper(localName = "GetFilePathbyReservedFieldsResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetFilePathbyReservedFieldsResponse")
    public WebSDKReturn getFilePathbyReservedFields(
        @WebParam(name = "reservedFields", targetNamespace = "http://www.voicecyber.com/")
        String reservedFields);

    /**
     * 
     * @param recordReference
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "SaveRecordFile", action = "http://www.voicecyber.com/IWebSDK/SaveRecordFile")
    @WebResult(name = "SaveRecordFileResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "SaveRecordFile", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.SaveRecordFile")
    @ResponseWrapper(localName = "SaveRecordFileResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.SaveRecordFileResponse")
    public WebSDKReturn saveRecordFile(
        @WebParam(name = "RecordReference", targetNamespace = "http://www.voicecyber.com/")
        String recordReference);

    /**
     * 
     * @param recordReference
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetRecordArchiveStatus", action = "http://www.voicecyber.com/IWebSDK/GetRecordArchiveStatus")
    @WebResult(name = "GetRecordArchiveStatusResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetRecordArchiveStatus", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRecordArchiveStatus")
    @ResponseWrapper(localName = "GetRecordArchiveStatusResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRecordArchiveStatusResponse")
    public WebSDKReturn getRecordArchiveStatus(
        @WebParam(name = "RecordReference", targetNamespace = "http://www.voicecyber.com/")
        String recordReference);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "UpdateRecordDataByExt", action = "http://www.voicecyber.com/IWebSDK/UpdateRecordDataByExt")
    @WebResult(name = "UpdateRecordDataByExtResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "UpdateRecordDataByExt", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UpdateRecordDataByExt")
    @ResponseWrapper(localName = "UpdateRecordDataByExtResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UpdateRecordDataByExtResponse")
    public WebSDKReturn updateRecordDataByExt(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param refID
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "UpdateRecordDataByID", action = "http://www.voicecyber.com/IWebSDK/UpdateRecordDataByID")
    @WebResult(name = "UpdateRecordDataByIDResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "UpdateRecordDataByID", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UpdateRecordDataByID")
    @ResponseWrapper(localName = "UpdateRecordDataByIDResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UpdateRecordDataByIDResponse")
    public WebSDKReturn updateRecordDataByID(
        @WebParam(name = "RefID", targetNamespace = "http://www.voicecyber.com/")
        String refID,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param ucid
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "UpdateRecordDataByUCID", action = "http://www.voicecyber.com/IWebSDK/UpdateRecordDataByUCID")
    @WebResult(name = "UpdateRecordDataByUCIDResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "UpdateRecordDataByUCID", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UpdateRecordDataByUCID")
    @ResponseWrapper(localName = "UpdateRecordDataByUCIDResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UpdateRecordDataByUCIDResponse")
    public WebSDKReturn updateRecordDataByUCID(
        @WebParam(name = "UCID", targetNamespace = "http://www.voicecyber.com/")
        String ucid,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param from
     * @param end
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetRecordListByStartRecordTime", action = "http://www.voicecyber.com/IWebSDK/GetRecordListByStartRecordTime")
    @WebResult(name = "GetRecordListByStartRecordTimeResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetRecordListByStartRecordTime", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRecordListByStartRecordTime")
    @ResponseWrapper(localName = "GetRecordListByStartRecordTimeResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRecordListByStartRecordTimeResponse")
    public WebSDKReturn getRecordListByStartRecordTime(
        @WebParam(name = "from", targetNamespace = "http://www.voicecyber.com/")
        String from,
        @WebParam(name = "end", targetNamespace = "http://www.voicecyber.com/")
        String end);

    /**
     * 
     * @param jsonOtherConditions
     * @param from
     * @param end
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetRecordList", action = "http://www.voicecyber.com/IWebSDK/GetRecordList")
    @WebResult(name = "GetRecordListResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetRecordList", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRecordList")
    @ResponseWrapper(localName = "GetRecordListResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRecordListResponse")
    public WebSDKReturn getRecordList(
        @WebParam(name = "from", targetNamespace = "http://www.voicecyber.com/")
        String from,
        @WebParam(name = "end", targetNamespace = "http://www.voicecyber.com/")
        String end,
        @WebParam(name = "JsonOtherConditions", targetNamespace = "http://www.voicecyber.com/")
        String jsonOtherConditions);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "StartRecord", action = "http://www.voicecyber.com/IWebSDK/StartRecord")
    @WebResult(name = "StartRecordResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "StartRecord", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StartRecord")
    @ResponseWrapper(localName = "StartRecordResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StartRecordResponse")
    public WebSDKReturn startRecord(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "StopRecord", action = "http://www.voicecyber.com/IWebSDK/StopRecord")
    @WebResult(name = "StopRecordResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "StopRecord", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StopRecord")
    @ResponseWrapper(localName = "StopRecordResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StopRecordResponse")
    public WebSDKReturn stopRecord(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "PauseRecord", action = "http://www.voicecyber.com/IWebSDK/PauseRecord")
    @WebResult(name = "PauseRecordResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "PauseRecord", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.PauseRecord")
    @ResponseWrapper(localName = "PauseRecordResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.PauseRecordResponse")
    public WebSDKReturn pauseRecord(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "ResumeRecord", action = "http://www.voicecyber.com/IWebSDK/ResumeRecord")
    @WebResult(name = "ResumeRecordResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "ResumeRecord", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.ResumeRecord")
    @ResponseWrapper(localName = "ResumeRecordResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.ResumeRecordResponse")
    public WebSDKReturn resumeRecord(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "StartRecordF", action = "http://www.voicecyber.com/IWebSDK/StartRecordF")
    @WebResult(name = "StartRecordFResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "StartRecordF", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StartRecordF")
    @ResponseWrapper(localName = "StartRecordFResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StartRecordFResponse")
    public WebSDKReturn startRecordF(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "StopRecordF", action = "http://www.voicecyber.com/IWebSDK/StopRecordF")
    @WebResult(name = "StopRecordFResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "StopRecordF", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StopRecordF")
    @ResponseWrapper(localName = "StopRecordFResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.StopRecordFResponse")
    public WebSDKReturn stopRecordF(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "PauseRecordF", action = "http://www.voicecyber.com/IWebSDK/PauseRecordF")
    @WebResult(name = "PauseRecordFResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "PauseRecordF", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.PauseRecordF")
    @ResponseWrapper(localName = "PauseRecordFResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.PauseRecordFResponse")
    public WebSDKReturn pauseRecordF(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param data
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "ResumeRecordF", action = "http://www.voicecyber.com/IWebSDK/ResumeRecordF")
    @WebResult(name = "ResumeRecordFResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "ResumeRecordF", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.ResumeRecordF")
    @ResponseWrapper(localName = "ResumeRecordFResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.ResumeRecordFResponse")
    public WebSDKReturn resumeRecordF(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "Data", targetNamespace = "http://www.voicecyber.com/")
        String data);

    /**
     * 
     * @param extension
     * @param agentID
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "AgentLogin", action = "http://www.voicecyber.com/IWebSDK/AgentLogin")
    @WebResult(name = "AgentLoginResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "AgentLogin", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.AgentLogin")
    @ResponseWrapper(localName = "AgentLoginResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.AgentLoginResponse")
    public WebSDKReturn agentLogin(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension,
        @WebParam(name = "AgentID", targetNamespace = "http://www.voicecyber.com/")
        String agentID);

    /**
     * 
     * @param extension
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "Agentlogout", action = "http://www.voicecyber.com/IWebSDK/Agentlogout")
    @WebResult(name = "AgentlogoutResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "Agentlogout", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.Agentlogout")
    @ResponseWrapper(localName = "AgentlogoutResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.AgentlogoutResponse")
    public WebSDKReturn agentlogout(
        @WebParam(name = "Extension", targetNamespace = "http://www.voicecyber.com/")
        String extension);

    /**
     * 
     * @param condition
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetRefIDByReservedField", action = "http://www.voicecyber.com/IWebSDK/GetRefIDByReservedField")
    @WebResult(name = "GetRefIDByReservedFieldResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetRefIDByReservedField", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRefIDByReservedField")
    @ResponseWrapper(localName = "GetRefIDByReservedFieldResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetRefIDByReservedFieldResponse")
    public WebSDKReturn getRefIDByReservedField(
        @WebParam(name = "condition", targetNamespace = "http://www.voicecyber.com/")
        String condition);

    /**
     * 
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "SubscribeRecordingStopEvent", action = "http://www.voicecyber.com/IWebSDK/SubscribeRecordingStopEvent")
    @WebResult(name = "SubscribeRecordingStopEventResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "SubscribeRecordingStopEvent", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.SubscribeRecordingStopEvent")
    @ResponseWrapper(localName = "SubscribeRecordingStopEventResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.SubscribeRecordingStopEventResponse")
    public WebSDKReturn subscribeRecordingStopEvent();

    /**
     * 
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "UnsubscribeRecordingStopEvent", action = "http://www.voicecyber.com/IWebSDK/UnsubscribeRecordingStopEvent")
    @WebResult(name = "UnsubscribeRecordingStopEventResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "UnsubscribeRecordingStopEvent", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UnsubscribeRecordingStopEvent")
    @ResponseWrapper(localName = "UnsubscribeRecordingStopEventResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.UnsubscribeRecordingStopEventResponse")
    public WebSDKReturn unsubscribeRecordingStopEvent();

    /**
     * 
     * @param extension
     * @return
     *     returns com.voicecyber.WebSDKReturn
     */
    @WebMethod(operationName = "GetExtensionStatus", action = "http://www.voicecyber.com/IWebSDK/GetExtensionStatus")
    @WebResult(name = "GetExtensionStatusResult", targetNamespace = "http://www.voicecyber.com/")
    @RequestWrapper(localName = "GetExtensionStatus", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetExtensionStatus")
    @ResponseWrapper(localName = "GetExtensionStatusResponse", targetNamespace = "http://www.voicecyber.com/", className = "com.voicecyber.GetExtensionStatusResponse")
    public WebSDKReturn getExtensionStatus(
        @WebParam(name = "extension", targetNamespace = "http://www.voicecyber.com/")
        String extension);

}
