
package cn.sh.ideal.voicecyber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.helpers.LogLog;

import cn.sh.ideal.util.ConfigProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebSDK", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192"+".168"+".4."+"78"+":9000/VCLogWebSDK/WebSDK?wsdl")
public class WebSDK
    extends Service
{

    private final static URL WEBSDK_WSDL_LOCATION;

    static {
        URL url = null;
        try {
        	
            url = new URL("http://"+ConfigProperties.getProperty("wsdlLocation")+"/VCLogWebSDK/WebSDK?wsdl");
        } catch (MalformedURLException e) {
            LogLog.error("异常"+e);
        }
        WEBSDK_WSDL_LOCATION = url;
    }

    public WebSDK(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebSDK() {
        super(WEBSDK_WSDL_LOCATION, new QName("http://tempuri.org/", "WebSDK"));
    }

    /**
     * 
     * @return
     *     returns IWebSDK
     */
    @WebEndpoint(name = "BasicHttpBinding_IWebSDK")
    public IWebSDK getBasicHttpBindingIWebSDK() {
        return (IWebSDK)super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWebSDK"), IWebSDK.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebSDK
     */
    @WebEndpoint(name = "BasicHttpBinding_IWebSDK")
    public IWebSDK getBasicHttpBindingIWebSDK(WebServiceFeature... features) {
        return (IWebSDK)super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWebSDK"), IWebSDK.class, features);
    }

}
