/* 默认数据列表 */
var CustomersData = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_01",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"发起需求"
		},{
			"gd_number": "DH17002",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_02",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17003",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_03",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17004",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_04",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"修改需求"
		},{
			"gd_number": "DH17005",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"领导驳回"
		}		
	],
	Total: 5
};
/* 需求工单录入 数据列表 */
var CustomersData_1 = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_01",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"发起需求"
		},{
			"gd_number": "DH17002",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_02",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17003",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_03",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17004",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_04",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"修改需求"
		},{
			"gd_number": "DH17005",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"领导驳回"
		}		
	],
	Total: 5
};
/* 需求工单审批 数据列表 */
var CustomersData_2 = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_01",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17002",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_02",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17003",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_03",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17004",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_04",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		},{
			"gd_number": "DH17005",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待领导审批"
		}		
	],
	Total: 5
};
/* 需求工单审核 数据列表 */
var CustomersData_3 = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_01",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人审核"
		},{
			"gd_number": "DH17002",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_02",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人审核"
		},{
			"gd_number": "DH17003",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_03",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"修改申请"
		},{
			"gd_number": "DH17004",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_04",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"修改申请"
		},{
			"gd_number": "DH17005",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"部门需求管理员取消"
		},{
			"gd_number": "DH17006",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"部门需求管理员取消"
		},{
			"gd_number": "DH17007",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"完成待归口人审核"
		},{
			"gd_number": "DH17008",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"完成待归口人审核"
		}	
	],
	Total: 5
};
/* 需求工单处理 数据列表 */
var CustomersData_4 = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_01",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"已派发"
		},{
			"gd_number": "DH17002",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_02",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"已派发"
		},{
			"gd_number": "DH17003",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_03",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"已派发"
		},{
			"gd_number": "DH17004",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_04",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"已接收"
		},{
			"gd_number": "DH17005",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"已接收"
		}		
	],
	Total: 5
};
/* 需求工单确认 数据列表 */
var CustomersData_5 = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_title": "新增技能配置功能_01",
			"queren_time":"2016-11-10 10:20",
			"queren_status":"未确认"
		},{
			"gd_number": "DH17002",
			"gd_title": "新增技能配置功能_02",
			"queren_time":"2016-11-10 10:20",
			"queren_status":"未确认"			
		},{
			"gd_number": "DH17003",
			"gd_title": "新增技能配置功能_03",
			"queren_time":"2016-11-10 10:20",
			"queren_status":"未确认"			
		},{
			"gd_number": "DH17004",
			"gd_title": "新增技能配置功能_04",
			"queren_time":"2016-11-10 10:20",
			"queren_status":"已确认"			
		},{
			"gd_number": "DH17005",
			"gd_title": "新增技能配置功能_05",
			"queren_time":"2016-11-10 10:20",
			"queren_status":"已确认"			
		}	
	],
	Total: 5
};
/* 需求工单结单 数据列表 */
var CustomersData_6 = 
	{Rows: [
		{
			"gd_number": "DH17001",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_01",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17002",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_02",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17003",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_03",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17004",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_04",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17005",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17006",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17007",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		},{
			"gd_number": "DH17008",
			"gd_tichuren": "张三",
			"gd_tichubumen": "电话服务中心",
			"gd_tichutime": "2016-09-10 14:39",
			"gd_qiwang_time": "2016-11-10 10:20",
			"gd_tichuren_phone": "189xxxxxxxx",
			"gd_tichuren_email": "189xxx@xx.cn",
			"gd_type": "业务类工单",
			"gd_bg_ty": "技能类",
			"gd_sm_ty": "技能小类1",
			"is_bd": "否",
			"gd_title": "新增技能配置功能_05",
			"gd_fbmgly":"小艾",
			"gd_fbmgly_phone":"189xxxxxxxx",
			"gd_fbmgly_email":"189xxx@xx.cn",
			"gd_status":"待归口人结单处理"
		}	
	],
	Total: 5
};